config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  resources :lists do
    resources :items
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  validates :description, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items

  validates :name, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)
    if @item.save
      redirect_to list_path(@list)
    else
      render "lists/show" 
    end
  end

  private
    def item_params
      params.require(:item).permit(:description)
    end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @list = List.new
    @lists = List.all
  end

  def show
    #I need to load the list
    @list = List.find_by(id: params[:id])
    @item = @list.items.build
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      @lists = List.all
      render :index
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodomvcCodeAlong</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<section class="todoapp">
	<header class="header">
		<h1>Your Lists</h1>
    <%= form_for @list do |f| %>
			<%= f.text_field :name, class: "new-todo", :placeholder => (@list.errors.full_messages_for(:name).first || "Enter a new List Name..") %>
			<!-- take errors.message first. otherwise it will show empty array. Lecture2 video 57:30 -->
      <%= f.submit style: "display: none" %>
		<% end %>

	</header>

	<section class="main">
		<ul class="todo-list">
      <% @lists.each do |list| %>
      <li>
        <div class="view">
          <label><%= link_to list.name, list_path(list) %></label>
        </div>
      </li>
      <% end %>
    </ul>
	</section>

	<footer class="footer">
	</footer>
</section>

app/views/lists/show.html.erb
<section class="todoapp">
	<header class="header">
		<h1><%= @list.name %></h1>
		<%#= form_for Item.new, url: list_items_path(@list) do |f| %>
		<!-- create new item at controller -->
		<%= form_for [@list, @item] do |f| %>
      <%= f.text_field :description, class: "new-todo", :placeholder => (@item.errors.full_messages_for(:description).first || "Enter a new item..") %>
      <%= f.submit style: "display: none" %>
    <% end %>
	</header>

	<section class="main">
		<ul class="todo-list">
			<% @list.items.each do |item| %>
      <li>
        <div class="view">
					<label><%= item.description %></label>
        </div>
      </li>
			<% end %>
    </ul>
	</section>

	<footer class="footer">
	</footer>
</section>